### ISSUE TITLE
WH-40

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#10]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 2.0 refers to “WH-40”.
“As a Certification Team Member, I need a system that allows me to create reports of my workload, organize calendar events and report time spent on activities (WH-40), so that I can manage my work.”
“As a Certification Team Manager I want the system to track specialist time and transfer information to the WH-40 so that time is appropriately charged against a case.”

## Question/Comment
Please clarify the reference to WH-40. Is this an existing system or form?

**Comment by rrefoy** [comment]
The WH-40 is an existing, internal WHD form.
