### ISSUE TITLE
Technology Stack Preference

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#11]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 4.0
“Technology stack options that are already approved within DOL are listed below in declining order of preference: – Ruby on Rails – .NET or PHP”

## Question/Comment
If we do not select Ruby on Rails (the first one in the preference order), will this be considered a weakness for the purpose of evaluation?

**Comment by rrefoy** [comment]
That business decision would not necessarily be deemed a weakness, however, with all other elements being equal, choosing Ruby on Rails over other methods would result in a higher technical ranking.
