### ISSUE TITLE
DB2

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#13]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 4.0, Requirements
“Must interface with PostgreSQL and allow create, retrieve, update, and delete as appropriate for the user's permissions. Must allow for migration to DB2.”

Trello board
“Must interface with DB2”

## Question/Comment
What is meant by “Must allow for migration to DB2” and “Must interface with DB2”? Please clarify this non-functional requirement.

**Comment by rrefoy** [comment]
We are asking the awardee to build a tool using PostgreSQL as the database, which is not what DOL currently uses. To ensure future compatibility, we're asking that the awardee to ensure a seamless DB2 migration.
