### ISSUE TITLE
Form Functionality

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#14]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 4.0, Requirements
“Vendor will not be required to handle any of the following tasks:  Provide form functionality for data-entry”

## Question/Comment
The Requirements section states that providing “form functionality for data-entry” is *not* required.  However, several user needs from Section 2.0 and the Trello board refer to various form functionality.  Can this non-requirement be clarified further?  Does this mean that data-entry of the form is not required or that functionality specific to data-entry is not required?

**Comment by rrefoy** [comment]
The awardee will not be required to write any of the prompts in the form. They will provide form functionality. WHD does require data entry so that internal WHD users may manually enter applications.
