### ISSUE TITLE
RFQ OCI Clarification

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-DOL-WHD-14-c#15]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFQ documents
RFQ Section 7.a

## Question/Comment
In an effort to discern potential organizational conflicts of interest (OCI) with the applicants, are users only employers seeking certification to employ workers with disabilities and pay sub-minimum wages  to Workers with Disabilities under Section 14(c) of the Fair Labor Standards Act (FLSA). Please describe the users of the system. Is there a list of employers that is publicly available, possibly a website link, so that vendors can determine if there are potential OCI’s?

**Comment by rrefoy** [comment]
Employers seeking certification will be the only users applying through the system. A list of certificate holders, as of January 1, 2016, is posted here (https://www.dol.gov/whd/workerswithdisabilities/employers.htm) under the header, “Certificate Holders”. It is the vendors responsibility to ensure there is not an organizational conflict of interest based on the list of certificate holders.
