### ISSUE TITLE
Estimated Number of Users of the System

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-DOL-WHD-14-c#16]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFQ documents
Attachment 1 PWS 2.0 Objectives

## Question/Comment
What is the estimated number of users of the system?

**Comment by rrefoy** [comment]
Current usage is under 3,000.
