### ISSUE TITLE
Period of Performance Estimation - Calendar Days Versus Government Business Days

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-DOL-WHD-14-c#17]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFQ documents
Attachment 1 PWS Section 5.7.3 and 6.2

## Question/Comment
Can we assume that the estimated level of effort is 60 government business days (as opposed to calendar days)?

**Comment by rrefoy** [comment]
60 Calendar Days.
