### ISSUE TITLE
RFQ - Period of Performance

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-DOL-WHD-14-c#18]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFQ documents
RFQ 3.0

## Question/Comment
Is the Period of Performance 60 calendar days or 60 government business days?

**Comment by rrefoy** [comment]
60 Calendar Days.
