### ISSUE TITLE
Desired Skills and Knowledge

### ISSUE THREAD

**Issue by sarahruggless** [18F/bpa-DOL-WHD-14-c#19]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
Sarah Ruggless, Flexion Inc.

## Section of RFQ documents
PWS
Section 5.7 Personnel
5.7.1. Desired Skills and Knowledge

## Question/Comment
The PWS states that the team must have the “Ability to utilize existing design and user experience assets from US Web Design Standards.” Is there an existing design that will be used or will the vendor need to provide the UX design capability to develop a design for this site?

**Comment by rrefoy** [comment]
Awardee will be required to work with 18F and DOL POCs to develop design.
