### ISSUE TITLE
Section 2.0 Objectives - Question

### ISSUE THREAD

**Issue by ktabor** [18F/bpa-DOL-WHD-14-c#24]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
{please provide information about your job/role in the Agile BPA process as well as your organization} 

Katherine Tabor; Systems Analyst
Three Wire Systems, Inc

## Section of RFQ documents
{please be specific about the section of the RFQ documents you have a question or comment about, if applicable}  

PWS
Section 2.0 Objectives

## Question/Comment

Please specify which file types the application must support in the upload feature. If there are no restrictions (i.e., any file type must be supported), please indicate so.

**Comment by rrefoy** [comment]
File types should include: docx, .pdf, .jpg, .csv, .xlsx
