### ISSUE TITLE
Section 4.0 Requirements - ATO

### ISSUE THREAD

**Issue by ktabor** [18F/bpa-DOL-WHD-14-c#25]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
{please provide information about your job/role in the Agile BPA process as well as your organization} 

Katherine Tabor; Systems Analyst
Three Wire Systems, Inc

## Section of RFQ documents
{please be specific about the section of the RFQ documents you have a question or comment about, if applicable}  

PWS
Section 4.0 Requirements

## Question/Comment

Authority to Operate, what would our involvement specifically be?

**Comment by rrefoy** [comment]
At a minimum, the awardee will be required to work with and adhere to any requests set by the OCIO at DOL in order to receive ATO.
