### ISSUE TITLE
Section 4.0 Requirements - Environment 

### ISSUE THREAD

**Issue by ktabor** [18F/bpa-DOL-WHD-14-c#26]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation
{please provide information about your job/role in the Agile BPA process as well as your organization} 

Katherine Tabor; Systems Analyst
Three Wire Systems, Inc

## Section of RFQ documents
{please be specific about the section of the RFQ documents you have a question or comment about, if applicable}  

PWS
Section 4.0 Requirements

## Question/Comment

Can the application be deployed in a GovCloud environment?

**Comment by rrefoy** [comment]
This tool will not need to be deployed to a GovCloud environment.
