### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#27]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 5.5.1 Transition Plan
“Ensure and agree that all deliverables, products, licenses, designs, data, documentation, tests, user research notes, source code, configuration settings and files, and materials developed throughout this task order will be the property of the U.S. Government and in the public domain.”

## Question/Comment
The PWS references “user research notes” but does not include specific user research requirements. Is further user research expected during the 60 day period of performance or has all user research already been completed?

**Comment by rrefoy** [comment]
The awardee will not be expected to do additional user research. 18F and WHD have done extensive user research and WHD will continue to do user research.
