### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#28]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
RFQ

## Question/Comment
There is a GitHub repo (https://github.com/18F/14c-prototype) with code for a 14(c) prototype. Is this prototype related to this RFQ and will it be integrated into the new system?

**Comment by rrefoy** [comment]
This prototype was not successfully delivered and will not be used for this requirement
