### ISSUE TITLE
Paper Applications

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#29]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 2.0 Objectives
“As an Applicant, I want to submit my application via a web form so that the submission process is quicker and I no longer have to mail my application. Acceptance Criteria (AC): Data will end up in a database. AC: The applicant must be logged in.”

## Question/Comment
Will mailed applications continue to be accepted?  Does the new system need to account for paper applications being processed?

**Comment by rrefoy** [comment]
Yes, we will continue to accept mailed applications. It would be ideal for the system to allow certification team specialists to manually enter the application data into the system. This would allow us to have all application data in one place.
