### ISSUE TITLE
Sensitive Document Redaction

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#30]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 4.0 Requirements
“System should advise users to redact Social Security Number (SSN) before uploading sensitive documents or the system will redact upon uploading.” 

## Question/Comment
Is there an existing service that will perform redacting functionality on uploaded documents? Or is scanning files for sensitive information and performing redaction a requirement that is expected to be built for this system?

**Comment by rrefoy** [comment]
There is no existing service that performs redacting functionality on uploaded documents. If released, shared or printed, the system will need to have the scanning function for sensitive information and perform redaction in the applicable fields.
