### ISSUE TITLE
Past Performance Clarification

### ISSUE THREAD

**Issue by sbedns** [18F/bpa-DOL-WHD-14-c#31]
# Question/Comment on Department of Labor 14(c) RFQ
Past Performance Clarification

## Name and affiliation
Shaun Edens - Product Owner, Scrum Master, and SAFe Agilist

## Section of RFQ documents
Reference 7.b.iii.ii
The RFQ states that similar experience is for projects of between 3 and five developers and between 2 and 12 months.  

## Question/Comment
Will projects with more than five FTE’s or lasting more than 12 months fail technical compliance check?

**Comment by rrefoy** [comment]
In order to ensure technical compliance, vendors must adhere to the criteria set forth in Section 7(b) of the RFQ.
