### ISSUE TITLE
Number of Users

### ISSUE THREAD

**Issue by sbedns** [18F/bpa-DOL-WHD-14-c#32]
# Question/Comment on Department of Labor 14(c) RFQ
Number of users

## Name and affiliation
Shaun Edens - Product Owner, Scrum Master, and SAFe Agilist

## Section of RFQ documents
Reference 7.b.iii.iii
The RFQ states that the experience should be for a web site serving over one million users.

## Question/Comment
Is there any guidance for determining if the project serves over one million users?  

Does the million number refer to all users that have addressed the web site or the potential pool of users or the annual user of the site or something else?

Is there any requirement for concurrent users? 

Would projects that deliver a website that serves less than one million users pass the technical compliance check?

**Comment by rrefoy** [comment]
"Section 7(b)(iii) of the RFQ will be amended to ""Recent and similar technical scope is past experience with building usable, responsive, consumer facing website with user accounts that is accessible to the public, built within the past three (3) years.""
