### ISSUE TITLE
User Story Requirements

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#33]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 2.0, Objectives - [Trello board](https://trello.com/b/74MUGMpP)

## Question/Comment
The Trello board and pages 1-3 of the PWS contain user stories for the Section 14(c) system. These include login for multiple roles (e.g., employer, applicant certification reviewer); data entry of the certification form with data validation checks; a search function to view submitted certifications; status email notifications; a reports capability; significant workflow (e.g., ability to assign and reassign applications to reviewers, maintain diary/review notes, workload reports, organize calendar events, keep track of time spent); ability to track applications through various statuses (pending, issued, withdrawn, amending denied, revoked, and expired) and a mechanism for status checking; and an online calculator. 

Are all user stories listed on the Trello board and PWS considered requirements and expected to be completed within 60 calendar days? Will the government consider extending the period of performance to allow more time to complete all user stories?

**Comment by rrefoy** [comment]
All user stories listed on the Trello board and the PWS will need to be completed during the 60 calendar day period of performance. Second paragraph of 2.0 states "These user needs shall be met in order to fulfill the objectives for performance of this task order, and may be refined by later sprints to continuously meet user needs."
