### ISSUE TITLE
Similar Experience

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#34]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
RFQ, 7.b.iii Similar Experience.
“The offeror shall provide at least one example of a scrum team that has worked on highly sensitive or highly complex projects in close collaboration with an agency, either federal, state or local.”
“The summary shall include links to the public Git repository that includes the source code that was developed and accepted for the project. Actual access to a publicly available Git repository is strongly encouraged over screenshots of private repositories.“

## Question/Comment
Many federal agencies don’t allow public repositories, especially for highly sensitive and highly complex projects. Will it be considered a weakness as part of the evaluation process to provide screen shots for our similar experience?

**Comment by rrefoy** [comment]
The Government understands that some agencies may prevent the sharing of the types of repositories that are being requested.  Therefore, screenshots will be acceptable for submission if such access cannot be provided. However, in accordance with Section 7(b)(iii)(i) of the RFQ, if screenshots are provided in lieu of live links, a brief explanation shall be provided.
