### ISSUE TITLE
Publicly-available API

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-DOL-WHD-14-c#35]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation

Patrick McConnell, SemanticBits, Agile BPA Manager

## Section of RFQ documents

5.7.1. Desired Skills and Knowledge

> Incorporating data in JSON or CSV format from a publicly-available Application Program Interface (API) into a website via a client-side request.

## Question/Comment

What is the public API referred to above?

**Comment by rrefoy** [comment]
The deadline to submit questions was Monday, July 18th at 6pm EST.
