### ISSUE TITLE
Period of Performance

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-DOL-WHD-14-c#36]
# Question/Comment on Department of Labor 14(c) RFQ

## Name and affiliation

Patrick McConnell, SemanticBits, Agile BPA Manager

## Section of RFQ documents

>3. Period of Performance. The Period of Performance (POP) is 60 days with no option periods.

and

>2.0 OBJECTIVES

## Question/Comment

There are numerous complexities in this project, including:

- Authentication 
- Role-based authorization for seven roles (Applicant, Parent, Certification Team Member, Certification Team Manager, Policy Team Member, Wage and Hour Investigator, WHD Field Manager)
- Building a web form, including validation, conditional logic, save partial forms, pre-population, file upload
- Data searching, sorting, viewing, full-text query
- History logging
- Work assignment
- Notifications, including receipt and status confirmations
- Reporting, including inventory reports, general reporting, and producing trend data
- Data import and export
- Workload management, including calendaring, time reporting, metrics
- System integration, including WHISARD and CPS
- Online calculator functionality

Two months may be an extremely risky timeframe to implement a production system with all of these requirements, even with a very large team.  The functionality alone is challenging to fit in this timeframe, as well as there being numerous touch points that rely on other parties (authentication, integration, wireframe/mockup review, etc.).

Will the government consider an increase in the period of performance?

**Comment by rrefoy** [comment]
The deadline to submit questions was Monday, July 18th at 6pm EST.

**Comment by patrickmcconnell** [comment]
@rrefoy , understood.  I hope the government still considers this important question.  For us, it is a bid/no-bid decision maker.

**Comment by patrickmcconnell** [comment]
@rrefoy , the due date for proposal submission was extended two days.  Is it possible to have the question submission deadline extended two days to 7/20?

**Comment by rrefoy** [comment]
The deadline for questions will not be extended.
