### ISSUE TITLE
Current Form

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#9]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 2.0 refers to using a web form to replace a mailed application.

## Question/Comment
Is the application based on the current [WH-226](https://www.dol.gov/whd/forms/wh226.pdf) form “Application for Authority to Employ Workers with Disabilities at Special Minimum Wages”? If yes, does the scope also include the [WH-226A](https://www.dol.gov/whd/forms/wh226a.pdf) form “Supplemental Data Sheet for Application for Authority to Employ Workers with Disabilities at Special Minimum Wages”?  If not, can you provide the current form being used?

**Comment by rrefoy** [comment]
These are the forms for current applications. Both of these forms are in the process of being revised. The awardee will be provided access to the proposed revisions of the forms.
